//! Optional, durable conversation compaction.
//!
//! A compaction never mutates a session projection directly. It first records
//! its intent, asks the configured LLM once, and replaces the selected surface
//! span only by appending a durable `user/message` replacement event.

use std::{
    collections::{BTreeMap, BTreeSet},
    sync::{Arc, Mutex, MutexGuard},
};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tessivum_core::{CancellationToken, ContextHandle, CoreError, ServiceHandle, ServiceKey};
use thiserror::Error;

use crate::{
    llm::LlmRuntime,
    protocol::{
        ContentBlock, FinishReason, GeneratePurpose, GenerateRequest, Message, MessageId,
        MessageRole, MessageSource, SessionEvent, SessionId, SurfaceOp,
    },
    session::{Session, SessionError, SurfaceMessage},
    TessivumError,
};

const DEFAULT_MAX_SURFACE_MESSAGES: usize = 512;
const DEFAULT_MAX_INPUT_CODEPOINTS: usize = 65_536;
const DEFAULT_MAX_SUMMARY_CODEPOINTS: usize = 16_384;
const COMPACTION_PLUGIN: &str = "compact";
const DEFAULT_SYSTEM_PROMPT: &str = "Summarize the supplied conversation faithfully. Return only the summary as plain text; do not call tools.";

/// Stable key for the optional durable compaction service.
pub fn compaction_service_key() -> ServiceKey {
    ServiceKey::new("harness.compaction", "1")
}

/// The caller-visible reason that selected this compaction attempt.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum CompactionTrigger {
    Manual,
    Pressure,
    ContextOverflow,
}

/// An inclusive range of positions on the *current* session surface.
///
/// These are indexes into [`Session::surface`], not event sequence numbers.
/// `SurfaceOp::Replace` is end-exclusive, so the service converts this range at
/// its sole append boundary.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionRange {
    pub start: u64,
    pub end: u64,
}

/// Static, deterministic model route and resource bounds for one service.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionConfig {
    pub provider: String,
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    #[serde(default = "default_max_surface_messages")]
    pub max_surface_messages: usize,
    #[serde(default = "default_max_input_codepoints")]
    pub max_input_codepoints: usize,
    #[serde(default = "default_max_summary_codepoints")]
    pub max_summary_codepoints: usize,
}

impl Default for CompactionConfig {
    fn default() -> Self {
        Self {
            provider: String::new(),
            model: String::new(),
            max_tokens: None,
            system: None,
            max_surface_messages: DEFAULT_MAX_SURFACE_MESSAGES,
            max_input_codepoints: DEFAULT_MAX_INPUT_CODEPOINTS,
            max_summary_codepoints: DEFAULT_MAX_SUMMARY_CODEPOINTS,
        }
    }
}

impl CompactionConfig {
    /// Validates untrusted configuration before an LLM route is selected.
    pub fn validate(&self) -> Result<(), CompactionError> {
        if self.provider.trim().is_empty() {
            return Err(invalid(
                "INVALID_COMPACTION_PROVIDER",
                "compaction provider must not be empty",
                Value::Null,
            ));
        }
        if self.model.trim().is_empty() {
            return Err(invalid(
                "INVALID_COMPACTION_MODEL",
                "compaction model must not be empty",
                Value::Null,
            ));
        }
        if self.max_tokens == Some(0) {
            return Err(invalid(
                "INVALID_COMPACTION_MAX_TOKENS",
                "compaction maxTokens must be positive when present",
                Value::Null,
            ));
        }
        for (field, value) in [
            ("maxSurfaceMessages", self.max_surface_messages),
            ("maxInputCodepoints", self.max_input_codepoints),
            ("maxSummaryCodepoints", self.max_summary_codepoints),
        ] {
            if value == 0 {
                return Err(invalid(
                    "INVALID_COMPACTION_BOUND",
                    "compaction bounds must be positive",
                    json!({"field": field}),
                ));
            }
        }
        Ok(())
    }
}

/// Durable sequence numbers generated by a successful compaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionEventSeqs {
    pub start: u64,
    pub summary: u64,
    pub replacement: u64,
    pub end: u64,
}

/// Facts returned only after a complete durable compaction has been recorded.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionResult {
    pub compaction_id: String,
    pub trigger: CompactionTrigger,
    pub range: CompactionRange,
    pub shadowed_event_seqs: Vec<u64>,
    pub token_estimate: u64,
    pub event_seqs: CompactionEventSeqs,
}

/// A compact-now/pressure invocation either changed the current surface or did
/// nothing. No-op means no session event was written and no model call started.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum CompactionOutcome {
    Noop {
        trigger: CompactionTrigger,
        token_estimate: u64,
    },
    Compacted(CompactionResult),
}

/// Facts from a durable tool-result replacement.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolResultPruneResult {
    pub range: CompactionRange,
    pub source_event_seq: u64,
    pub replacement_event_seq: u64,
    pub original_codepoints: u64,
    pub retained_codepoints: u64,
}

/// A tool-result pruner does not write when the result is already within its
/// caller-provided codepoint bound.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ToolResultPruneOutcome {
    Noop {
        source_event_seq: u64,
        codepoints: u64,
    },
    Pruned(ToolResultPruneResult),
}

/// Failures reported by the compaction boundary.
#[derive(Clone, Debug, Error, PartialEq)]
pub enum CompactionError {
    #[error("compaction is already running for session {session}")]
    Busy { session: SessionId },
    #[error("compaction was cancelled")]
    Cancelled,
    #[error(transparent)]
    Invalid(TessivumError),
    #[error("LLM summarization failed: {0}")]
    Llm(TessivumError),
    #[error(transparent)]
    Session(#[from] SessionError),
}

impl CompactionError {
    /// Stable machine-readable error code for tool-facing callers.
    pub fn code(&self) -> &str {
        match self {
            Self::Busy { .. } => "COMPACTION_BUSY",
            Self::Cancelled => "CANCELLED",
            Self::Invalid(error) | Self::Llm(error) => &error.code,
            Self::Session(error) => error.code(),
        }
    }
}

/// A single optional service: it owns only its deterministic LLM configuration
/// and a first-wins per-session attempt set. Session durability remains owned
/// by [`Session`].
#[derive(Clone)]
pub struct CompactionService {
    llm: LlmRuntime,
    config: CompactionConfig,
    active: Arc<Mutex<BTreeSet<SessionId>>>,
}
impl std::fmt::Debug for CompactionService {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("CompactionService")
            .field("provider", &self.config.provider)
            .field("model", &self.config.model)
            .field("active_sessions", &lock(&self.active).len())
            .finish_non_exhaustive()
    }
}

impl CompactionService {
    /// Creates a service whose provider selection is fixed for its lifetime.
    pub fn new(llm: LlmRuntime, config: CompactionConfig) -> Result<Self, CompactionError> {
        config.validate()?;
        Ok(Self {
            llm,
            config,
            active: Arc::new(Mutex::new(BTreeSet::new())),
        })
    }

    /// Publishes this optional capability into a caller-owned context scope.
    pub fn publish(
        &self,
        context: &ContextHandle,
    ) -> Result<ServiceHandle<CompactionService>, CoreError> {
        context.provide(compaction_service_key(), self.clone())
    }

    pub fn config(&self) -> &CompactionConfig {
        &self.config
    }

    /// Compacts all current live-surface entries when at least two exist.
    ///
    /// A standalone idle entry is not useful context to summarize, so this is a
    /// strict no-op without a durable marker or model call.
    pub async fn compact_now(
        &self,
        session: &Session,
        cancellation: CancellationToken,
    ) -> Result<CompactionOutcome, CompactionError> {
        self.compact_automatic(session, CompactionTrigger::Manual, cancellation)
            .await
    }

    /// Handles a deterministic pressure or context-overflow trigger.
    pub async fn compact_for_trigger(
        &self,
        session: &Session,
        trigger: CompactionTrigger,
        cancellation: CancellationToken,
    ) -> Result<CompactionOutcome, CompactionError> {
        if trigger == CompactionTrigger::Manual {
            return Err(invalid(
                "INVALID_COMPACTION_TRIGGER",
                "automatic compaction requires pressure or context-overflow",
                Value::Null,
            ));
        }
        self.compact_automatic(session, trigger, cancellation).await
    }

    /// Compacts one caller-selected inclusive current-surface region.
    pub async fn compact_region(
        &self,
        session: &Session,
        range: CompactionRange,
        cancellation: CancellationToken,
    ) -> Result<CompactionResult, CompactionError> {
        check_cancellation(&cancellation)?;
        let _lease = self.acquire(session.id())?;
        let plan = self.plan(session, range)?;
        self.execute(session, CompactionTrigger::Manual, plan, cancellation)
            .await
    }

    /// Replaces one oversized active tool result with a deterministic Unicode
    /// codepoint prefix. The original surface is retained if this append fails.
    pub async fn prune_tool_result(
        &self,
        session: &Session,
        source_event_seq: u64,
        max_codepoints: u64,
        cancellation: CancellationToken,
    ) -> Result<ToolResultPruneOutcome, CompactionError> {
        check_cancellation(&cancellation)?;
        if max_codepoints == 0 {
            return Err(invalid(
                "INVALID_TOOL_RESULT_PRUNE_BOUND",
                "tool-result prune bound must be positive",
                Value::Null,
            ));
        }
        let _lease = self.acquire(session.id())?;
        let surface = session.surface();
        let expected_surface_event_seqs = surface
            .iter()
            .map(|entry| entry.event_seq)
            .collect::<Vec<_>>();
        let (position, entry) = surface
            .iter()
            .enumerate()
            .find(|(_, entry)| entry.event_seq == source_event_seq)
            .ok_or_else(|| {
                invalid(
                    "INACTIVE_TOOL_RESULT",
                    "tool-result source is not on the current surface",
                    json!({"sourceEventSeq": source_event_seq}),
                )
            })?;
        let (call_id, content, is_error) = tool_result(entry)?;
        let original = tool_output_text(content);
        let original_codepoints = codepoints(&original);
        if original_codepoints <= max_codepoints {
            return Ok(ToolResultPruneOutcome::Noop {
                source_event_seq,
                codepoints: original_codepoints,
            });
        }
        let text = truncate_codepoints(&original, max_codepoints);
        let retained_codepoints = codepoints(&text);
        let range = CompactionRange {
            start: position as u64,
            end: position as u64,
        };
        let replacement = Message {
            id: MessageId::from(format!("tool-prune-{source_event_seq}")),
            role: MessageRole::User,
            content: vec![ContentBlock::ToolResult {
                tool_call_id: call_id.clone(),
                content: vec![ContentBlock::Text { text }],
                is_error,
            }],
            source: MessageSource::Tool {
                call_id: call_id.clone(),
            },
        };
        let replacement_event_seq = append(
            session,
            AppendSpec {
                event_type: "tool/result",
                data: json!({
                    "message": replacement,
                    "pruned": {
                        "sourceEventSeq": source_event_seq,
                        "originalCodepoints": original_codepoints,
                        "retainedCodepoints": retained_codepoints,
                    },
                }),
                source_event_seqs: Some(vec![source_event_seq]),
                surface_op: Some(SurfaceOp::Replace {
                    start: range.start,
                    end: range.end + 1,
                }),
                expected_surface_event_seqs: Some(&expected_surface_event_seqs),
                ignorable: None,
            },
            cancellation,
        )
        .await?;
        Ok(ToolResultPruneOutcome::Pruned(ToolResultPruneResult {
            range,
            source_event_seq,
            replacement_event_seq,
            original_codepoints,
            retained_codepoints,
        }))
    }

    async fn compact_automatic(
        &self,
        session: &Session,
        trigger: CompactionTrigger,
        cancellation: CancellationToken,
    ) -> Result<CompactionOutcome, CompactionError> {
        check_cancellation(&cancellation)?;
        let _lease = self.acquire(session.id())?;
        let surface = session.surface();
        let seed_seqs = session
            .seed_events()
            .into_iter()
            .map(|event| event.seq)
            .collect::<BTreeSet<_>>();
        // A seed can contain an imported orphan. Automatic compaction only
        // considers live entries, so old seed anomalies do not block it.
        let first_live = surface
            .iter()
            .position(|entry| !seed_seqs.contains(&entry.event_seq))
            .unwrap_or(surface.len());
        let live_len = surface.len().saturating_sub(first_live);
        if live_len < 2 {
            return Ok(CompactionOutcome::Noop {
                trigger,
                token_estimate: 0,
            });
        }
        let range = CompactionRange {
            start: first_live as u64,
            end: (surface.len() - 1) as u64,
        };
        let plan = self.plan_from_surface(&surface, range)?;
        let result = self.execute(session, trigger, plan, cancellation).await?;
        Ok(CompactionOutcome::Compacted(result))
    }

    fn acquire(&self, session: SessionId) -> Result<CompactionLease, CompactionError> {
        let mut active = lock(&self.active);
        if !active.insert(session.clone()) {
            return Err(CompactionError::Busy { session });
        }
        Ok(CompactionLease {
            active: Arc::clone(&self.active),
            session,
        })
    }

    fn plan(&self, session: &Session, range: CompactionRange) -> Result<Plan, CompactionError> {
        self.plan_from_surface(&session.surface(), range)
    }

    fn plan_from_surface(
        &self,
        surface: &[SurfaceMessage],
        range: CompactionRange,
    ) -> Result<Plan, CompactionError> {
        let selected = range_slice(surface, range)?;
        if selected.len() > self.config.max_surface_messages {
            return Err(invalid(
                "COMPACTION_REGION_TOO_LARGE",
                "compaction region exceeds the configured message bound",
                json!({
                    "messages": selected.len(),
                    "maximum": self.config.max_surface_messages,
                }),
            ));
        }
        validate_tool_pairs(surface, range)?;
        let messages = selected
            .iter()
            .map(|entry| entry.message.clone())
            .collect::<Vec<_>>();
        let input_codepoints = messages
            .iter()
            .map(serialized_codepoints)
            .try_fold(0_u64, |total, count| {
                count.and_then(|count| total.checked_add(count).ok_or(()))
            })
            .map_err(|_| {
                invalid(
                    "COMPACTION_INPUT_TOO_LARGE",
                    "compaction input is too large to count safely",
                    Value::Null,
                )
            })?;
        if input_codepoints > self.config.max_input_codepoints as u64 {
            return Err(invalid(
                "COMPACTION_INPUT_TOO_LARGE",
                "compaction input exceeds the configured codepoint bound",
                json!({
                    "codepoints": input_codepoints,
                    "maximum": self.config.max_input_codepoints,
                }),
            ));
        }
        Ok(Plan {
            range,
            expected_surface_event_seqs: surface.iter().map(|entry| entry.event_seq).collect(),
            shadowed_event_seqs: selected.iter().map(|entry| entry.event_seq).collect(),
            messages,
            token_estimate: tokens_for(input_codepoints),
        })
    }

    async fn execute(
        &self,
        session: &Session,
        trigger: CompactionTrigger,
        plan: Plan,
        cancellation: CancellationToken,
    ) -> Result<CompactionResult, CompactionError> {
        check_cancellation(&cancellation)?;
        let compaction_id = uuid::Uuid::new_v4().to_string();
        let turn = open_turn(session);
        let start_seq = append(
            session,
            AppendSpec {
                event_type: "compaction/start",
                data: json!({
                    "compactionId": compaction_id.clone(),
                    "turn": turn,
                }),
                source_event_seqs: None,
                surface_op: None,
                expected_surface_event_seqs: None,
                ignorable: Some(true),
            },
            cancellation.clone(),
        )
        .await?;
        let request = GenerateRequest {
            provider: self.config.provider.clone(),
            model: self.config.model.clone(),
            reasoning_effort: None,
            messages: plan.messages.clone(),
            system: Some(
                self.config
                    .system
                    .clone()
                    .unwrap_or_else(|| DEFAULT_SYSTEM_PROMPT.into()),
            ),
            tools: None,
            temperature: None,
            max_tokens: self.config.max_tokens,
            stop: None,
            session_id: Some(session.id()),
            purpose: Some(GeneratePurpose::Compaction),
        };
        let generation = match self.llm.complete(request, cancellation.clone()).await {
            Ok(generation) => {
                if cancellation.is_cancelled() {
                    return self
                        .finish_error(
                            session,
                            &compaction_id,
                            start_seq,
                            &plan,
                            CompactionError::Cancelled,
                        )
                        .await;
                }
                generation
            }
            Err(error) => {
                let error = if cancellation.is_cancelled() {
                    CompactionError::Cancelled
                } else {
                    CompactionError::Llm(error)
                };
                return self
                    .finish_error(session, &compaction_id, start_seq, &plan, error)
                    .await;
            }
        };
        match &generation.finish_reason {
            FinishReason::Stop => {}
            FinishReason::Aborted { .. } => {
                return self
                    .finish_error(
                        session,
                        &compaction_id,
                        start_seq,
                        &plan,
                        CompactionError::Cancelled,
                    )
                    .await;
            }
            FinishReason::Error { failure } => {
                return self
                    .finish_error(
                        session,
                        &compaction_id,
                        start_seq,
                        &plan,
                        CompactionError::Llm(TessivumError::new(
                            failure.code.clone(),
                            failure.message.clone(),
                            "llm",
                            serde_json::to_value(failure).unwrap_or(Value::Null),
                        )),
                    )
                    .await;
            }
            FinishReason::ToolCalls | FinishReason::MaxTokens => {
                return self
                    .finish_error(
                        session,
                        &compaction_id,
                        start_seq,
                        &plan,
                        invalid(
                            "INVALID_COMPACTION_SUMMARY",
                            "compaction summary must finish normally without tool calls",
                            json!({"finishReason": generation.finish_reason}),
                        ),
                    )
                    .await;
            }
        }
        let summary = match summary_blocks(&generation.message, self.config.max_summary_codepoints)
        {
            Ok(summary) => summary,
            Err(error) => {
                return self
                    .finish_error(session, &compaction_id, start_seq, &plan, error)
                    .await;
            }
        };
        let summary_seq = match append(
            session,
            AppendSpec {
                event_type: "compaction/summary",
                data: json!({
                    "compactionId": compaction_id.clone(),
                    "summary": summary.clone(),
                    "rawOutput": generation.message.content,
                    "provider": self.config.provider.clone(),
                    "model": self.config.model.clone(),
                    "llmStreamCall": true,
                    "shadowedRange": {
                        "start": plan.shadowed_event_seqs.first(),
                        "end": plan.shadowed_event_seqs.last(),
                    },
                    "shadowedSeqs": plan.shadowed_event_seqs.clone(),
                    "shadowedTokenCount": plan.token_estimate,
                    "usage": generation.usage,
                }),
                source_event_seqs: None,
                surface_op: None,
                expected_surface_event_seqs: None,
                ignorable: Some(true),
            },
            cancellation.clone(),
        )
        .await
        {
            Ok(seq) => seq,
            Err(error) => {
                return self
                    .finish_error(
                        session,
                        &compaction_id,
                        start_seq,
                        &plan,
                        compaction_session_error(&cancellation, error),
                    )
                    .await;
            }
        };
        if cancellation.is_cancelled() {
            return self
                .finish_error(
                    session,
                    &compaction_id,
                    start_seq,
                    &plan,
                    CompactionError::Cancelled,
                )
                .await;
        }
        let replacement = Message {
            id: MessageId::from(format!("compaction-{start_seq}")),
            role: MessageRole::User,
            content: summary,
            source: MessageSource::Plugin {
                plugin: COMPACTION_PLUGIN.into(),
                compaction_id: Some(compaction_id.clone()),
                form: None,
                sections: None,
                summary: None,
            },
        };
        let mut sources = Vec::with_capacity(plan.shadowed_event_seqs.len() + 2);
        sources.push(start_seq);
        sources.push(summary_seq);
        sources.extend(plan.shadowed_event_seqs.iter().copied());
        let replacement_seq = match append(
            session,
            AppendSpec {
                event_type: "user/message",
                data: serde_json::to_value(replacement).expect("Message is serializable"),
                source_event_seqs: Some(sources),
                surface_op: Some(SurfaceOp::Replace {
                    start: plan.range.start,
                    end: plan.range.end.checked_add(1).ok_or_else(|| {
                        invalid(
                            "INVALID_COMPACTION_REGION",
                            "compaction range end cannot be represented as an exclusive bound",
                            json!({"end": plan.range.end}),
                        )
                    })?,
                }),
                expected_surface_event_seqs: Some(&plan.expected_surface_event_seqs),
                ignorable: None,
            },
            cancellation.clone(),
        )
        .await
        {
            Ok(seq) => seq,
            Err(error) => {
                return self
                    .finish_error(
                        session,
                        &compaction_id,
                        start_seq,
                        &plan,
                        compaction_session_error(&cancellation, error),
                    )
                    .await;
            }
        };
        let end_seq = append_end(
            session,
            EndSpec {
                compaction_id: &compaction_id,
                turn,
                error: None,
            },
        )
        .await?;
        Ok(CompactionResult {
            compaction_id,
            trigger,
            range: plan.range,
            shadowed_event_seqs: plan.shadowed_event_seqs,
            token_estimate: plan.token_estimate,
            event_seqs: CompactionEventSeqs {
                start: start_seq,
                summary: summary_seq,
                replacement: replacement_seq,
                end: end_seq,
            },
        })
    }

    async fn finish_error(
        &self,
        session: &Session,
        compaction_id: &str,
        _start_seq: u64,
        _plan: &Plan,
        error: CompactionError,
    ) -> Result<CompactionResult, CompactionError> {
        append_end(
            session,
            EndSpec {
                compaction_id,
                turn: open_turn(session),
                error: Some(&error),
            },
        )
        .await?;
        Err(error)
    }
}

struct CompactionLease {
    active: Arc<Mutex<BTreeSet<SessionId>>>,
    session: SessionId,
}

impl Drop for CompactionLease {
    fn drop(&mut self) {
        lock(&self.active).remove(&self.session);
    }
}

struct Plan {
    range: CompactionRange,
    expected_surface_event_seqs: Vec<u64>,
    shadowed_event_seqs: Vec<u64>,
    messages: Vec<Message>,
    token_estimate: u64,
}

struct AppendSpec<'a> {
    event_type: &'a str,
    data: Value,
    source_event_seqs: Option<Vec<u64>>,
    surface_op: Option<SurfaceOp>,
    expected_surface_event_seqs: Option<&'a [u64]>,
    ignorable: Option<bool>,
}

struct EndSpec<'a> {
    compaction_id: &'a str,
    turn: Option<u64>,
    error: Option<&'a CompactionError>,
}

async fn append(
    session: &Session,
    spec: AppendSpec<'_>,
    cancellation: CancellationToken,
) -> Result<u64, SessionError> {
    let seq = session.next_seq()?;
    let event = SessionEvent {
        event_type: spec.event_type.into(),
        seq,
        time: 0,
        data: spec.data,
        ignorable: spec.ignorable,
        source_event_seqs: spec.source_event_seqs,
        surface_op: spec.surface_op,
    };
    match spec.expected_surface_event_seqs {
        Some(expected) => {
            session
                .append_if_surface(event, expected, cancellation)
                .await?
        }
        None => session.append(event, cancellation).await?,
    }
    Ok(seq)
}

async fn append_end(session: &Session, spec: EndSpec<'_>) -> Result<u64, CompactionError> {
    let mut data = json!({
        "compactionId": spec.compaction_id,
        "turn": spec.turn,
    });
    if let Some(error) = spec.error {
        data["error"] = Value::String(error.to_string());
    }
    // A start event is already durable when this helper is reached. Closing
    // that durable attempt must not be defeated by the caller's cancellation.
    Ok(append(
        session,
        AppendSpec {
            event_type: "compaction/end",
            data,
            source_event_seqs: None,
            surface_op: None,
            expected_surface_event_seqs: None,
            ignorable: Some(true),
        },
        ContextHandle::root().scope().cancellation(),
    )
    .await?)
}

fn range_slice(
    surface: &[SurfaceMessage],
    range: CompactionRange,
) -> Result<&[SurfaceMessage], CompactionError> {
    let len = surface.len() as u64;
    if range.start > range.end || range.end >= len {
        return Err(invalid(
            "INVALID_COMPACTION_REGION",
            "compaction range must be ordered and inside the current surface",
            json!({"start": range.start, "end": range.end, "surfaceLength": len}),
        ));
    }
    let start = usize::try_from(range.start).map_err(|_| {
        invalid(
            "INVALID_COMPACTION_REGION",
            "compaction range start cannot be represented as a surface index",
            json!({"start": range.start}),
        )
    })?;
    let end = usize::try_from(range.end).map_err(|_| {
        invalid(
            "INVALID_COMPACTION_REGION",
            "compaction range end cannot be represented as a surface index",
            json!({"end": range.end}),
        )
    })?;
    Ok(&surface[start..=end])
}

fn validate_tool_pairs(
    surface: &[SurfaceMessage],
    range: CompactionRange,
) -> Result<(), CompactionError> {
    let mut pending = BTreeMap::<String, usize>::new();
    for (index, entry) in surface.iter().enumerate() {
        let inside = range.start <= index as u64 && index as u64 <= range.end;
        for call in tool_calls(&entry.message) {
            if let Some(previous) = pending.insert(call.clone(), index) {
                if inside || in_range(previous, range) {
                    return Err(invalid(
                        "INVALID_TOOL_PAIR_ORDER",
                        "a tool call id is active more than once",
                        json!({"toolCallId": call}),
                    ));
                }
            }
        }
        for result in tool_results(&entry.message) {
            match pending.remove(&result) {
                Some(call_index) if inside != in_range(call_index, range) => {
                    return Err(invalid(
                        "UNBALANCED_TOOL_PAIR",
                        "compaction region must contain both sides of every tool pair",
                        json!({"toolCallId": result}),
                    ));
                }
                Some(_) => {}
                None if inside => {
                    return Err(invalid(
                        "INVALID_TOOL_PAIR_ORDER",
                        "a selected tool result has no earlier active tool call",
                        json!({"toolCallId": result}),
                    ));
                }
                None => {}
            }
        }
    }
    if let Some((call, _)) = pending
        .into_iter()
        .find(|(_, index)| in_range(*index, range))
    {
        return Err(invalid(
            "UNBALANCED_TOOL_PAIR",
            "a selected tool call has no matching tool result",
            json!({"toolCallId": call}),
        ));
    }
    Ok(())
}

fn in_range(index: usize, range: CompactionRange) -> bool {
    range.start <= index as u64 && index as u64 <= range.end
}

fn tool_calls(message: &Message) -> Vec<String> {
    message
        .content
        .iter()
        .filter_map(|block| match block {
            ContentBlock::ToolCall { id, .. } => Some(id.as_str().to_owned()),
            _ => None,
        })
        .collect()
}

fn tool_results(message: &Message) -> Vec<String> {
    let mut results = Vec::new();
    for block in &message.content {
        collect_tool_results(block, &mut results);
    }
    results
}

fn collect_tool_results(block: &ContentBlock, results: &mut Vec<String>) {
    if let ContentBlock::ToolResult {
        tool_call_id,
        content,
        ..
    } = block
    {
        results.push(tool_call_id.as_str().to_owned());
        for block in content {
            collect_tool_results(block, results);
        }
    }
}

fn summary_blocks(
    message: &Message,
    max_codepoints: usize,
) -> Result<Vec<ContentBlock>, CompactionError> {
    let mut summary = Vec::new();
    let mut codepoints_count = 0_u64;
    for block in &message.content {
        match block {
            ContentBlock::Text { text } => {
                codepoints_count = codepoints_count.saturating_add(codepoints(text));
                summary.push(block.clone());
            }
            ContentBlock::Reasoning { .. } => {}
            ContentBlock::Image { .. }
            | ContentBlock::ToolCall { .. }
            | ContentBlock::ToolResult { .. } => {
                return Err(invalid(
                    "INVALID_COMPACTION_SUMMARY",
                    "compaction summary may contain only text and reasoning blocks",
                    Value::Null,
                ));
            }
        }
    }
    if summary.is_empty()
        || summary
            .iter()
            .all(|block| matches!(block, ContentBlock::Text { text } if text.trim().is_empty()))
    {
        return Err(invalid(
            "INVALID_COMPACTION_SUMMARY",
            "compaction summary must contain text",
            Value::Null,
        ));
    }
    if codepoints_count > max_codepoints as u64 {
        return Err(invalid(
            "COMPACTION_SUMMARY_TOO_LARGE",
            "compaction summary exceeds the configured codepoint bound",
            json!({"maximum": max_codepoints}),
        ));
    }
    Ok(summary)
}

fn open_turn(session: &Session) -> Option<u64> {
    let mut turn = None;
    for event in session.events() {
        match event.event_type.as_str() {
            "turn/start" => turn = event.data.get("turn").and_then(Value::as_u64),
            "turn/end" if event.data.get("turn").and_then(Value::as_u64) == turn => turn = None,
            _ => {}
        }
    }
    turn
}

fn tool_result(
    entry: &SurfaceMessage,
) -> Result<(&crate::protocol::ToolCallId, &[ContentBlock], Option<bool>), CompactionError> {
    let MessageSource::Tool { call_id } = &entry.message.source else {
        return Err(invalid(
            "INVALID_TOOL_RESULT",
            "selected surface entry is not a tool result",
            json!({"eventSeq": entry.event_seq}),
        ));
    };
    let [ContentBlock::ToolResult {
        tool_call_id,
        content,
        is_error,
    }] = entry.message.content.as_slice()
    else {
        return Err(invalid(
            "INVALID_TOOL_RESULT",
            "selected tool result must contain exactly one tool-result block",
            json!({"eventSeq": entry.event_seq}),
        ));
    };
    if call_id != tool_call_id {
        return Err(invalid(
            "INVALID_TOOL_RESULT",
            "tool result source does not match its content block",
            json!({"eventSeq": entry.event_seq}),
        ));
    }
    Ok((tool_call_id, content, *is_error))
}

fn tool_output_text(content: &[ContentBlock]) -> String {
    let mut output = String::new();
    for block in content {
        append_block_text(block, &mut output);
    }
    output
}

fn append_block_text(block: &ContentBlock, output: &mut String) {
    match block {
        ContentBlock::Text { text } | ContentBlock::Reasoning { text } => output.push_str(text),
        ContentBlock::Image { attachment } => output.push_str(&attachment.to_string()),
        ContentBlock::ToolCall {
            name, arguments, ..
        } => {
            output.push_str(name);
            output.push_str(arguments);
        }
        ContentBlock::ToolResult { content, .. } => {
            for block in content {
                append_block_text(block, output);
            }
        }
    }
}

fn truncate_codepoints(text: &str, max_codepoints: u64) -> String {
    let count = codepoints(text);
    if count <= max_codepoints {
        return text.to_owned();
    }
    if max_codepoints == 1 {
        return "…".into();
    }
    let prefix = text
        .chars()
        .take((max_codepoints - 1) as usize)
        .collect::<String>();
    format!("{prefix}…")
}

fn serialized_codepoints(message: &Message) -> Result<u64, ()> {
    let serialized = serde_json::to_string(message).map_err(|_| ())?;
    Ok(codepoints(&serialized))
}

fn codepoints(text: &str) -> u64 {
    text.chars().count() as u64
}

fn tokens_for(codepoints: u64) -> u64 {
    codepoints.saturating_add(3) / 4
}

fn invalid(code: &str, message: &str, details: Value) -> CompactionError {
    CompactionError::Invalid(TessivumError::new(code, message, "compaction", details))
}

fn compaction_session_error(
    cancellation: &CancellationToken,
    error: SessionError,
) -> CompactionError {
    if cancellation.is_cancelled() || matches!(&error, SessionError::Cancelled) {
        CompactionError::Cancelled
    } else {
        CompactionError::Session(error)
    }
}

fn check_cancellation(cancellation: &CancellationToken) -> Result<(), CompactionError> {
    if cancellation.is_cancelled() {
        Err(CompactionError::Cancelled)
    } else {
        Ok(())
    }
}

fn lock<T>(mutex: &Mutex<T>) -> MutexGuard<'_, T> {
    mutex.lock().unwrap_or_else(|poison| poison.into_inner())
}

fn default_max_surface_messages() -> usize {
    DEFAULT_MAX_SURFACE_MESSAGES
}

fn default_max_input_codepoints() -> usize {
    DEFAULT_MAX_INPUT_CODEPOINTS
}

fn default_max_summary_codepoints() -> usize {
    DEFAULT_MAX_SUMMARY_CODEPOINTS
}
